import type { Slug } from '@/shared/domain/types/slug'

export const Urls = {
  HOME: '/',
  EVENTS: '/events/',
  EVENTS_CREATE: '/events/create',
  EVENTS_WITH_PROVINCE: (province: string) => `${Urls.EVENTS}?province=${province}`,
  MEETUPS: '/meetups/',
  MEETUPS_CREATE: '/meetups/create',
  MEETUPS_WITH_PROVINCE: (province: string) => `${Urls.MEETUPS}?province=${province}`,
  EVENT: (slug: Slug) => `/events/${slug}`,
  EVENT_EDIT: (slug: Slug) => `/events/${slug}/edit`,
  MEETUP: (slug: Slug) => `/meetups/${slug}`,
  MEETUP_EDIT: (slug: Slug) => `/meetups/${slug}/edit`,
  PAST_EVENTS: '/events/past/',
  PAST_EVENTS_WITH_PROVINCE: (province: string) => `${Urls.PAST_EVENTS}?province=${province}`,
  PAST_MEETUPS: '/meetups/past/',
  PAST_MEETUPS_WITH_PROVINCE: (province: string) => `${Urls.PAST_MEETUPS}?province=${province}`,
  PROVINCE: (slug: Slug) => `/${slug}`,
  ORGANIZATIONS: `/organizations`,
  ORGANIZATION: (handle: string) => `${Urls.ORGANIZATIONS}/${handle}`,
  ORGANIZATION_EVENTS: (handle: string) => `${Urls.ORGANIZATIONS}/${handle}/events`,
  ORGANIZATION_MEETUPS: (handle: string) => `${Urls.ORGANIZATIONS}/${handle}/meetups`,
  ORGANIZATION_ORGANIZERS: (handle: string) => `${Urls.ORGANIZATIONS}/${handle}/organizers`,
  ORGANIZATION_EDIT: (handle: string) => `${Urls.ORGANIZATIONS}/${handle}/edit`,
  MY_ORGANIZATIONS: '/me/organizations/',
  MY_MEETUPS: '/me/meetups/',
  FOLLOWING_ORGANIZATIONS: '/me/organizations/following',
  MEMBER_ORGANIZATIONS: '/me/organizations/member',
  CREATE_ORGANIZATION: '/me/organizations/create',
  CREATE_EVENT: (handle: string) => `/organizations/${handle}/events/create`,
  CREATE_MEETUP: (handle: string) => `/organizations/${handle}/meetups/create`,
  CALENDAR: '/calendar',
  LOGIN: '/login',
  LOGIN_GITHUB: '/login/github',
  LOGIN_GOOGLE: '/login/google',
  LOGIN_TWITTER: '/login/twitter',
  LOGOUT: '/logout',
  PROFILE: '/me/profile',
  SETTINGS: '/me/settings',
  SETTINGS_ACCOUNT: '/me/settings/account',
  SETTINGS_NOTIFICATIONS: '/me/settings/notifications',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  CHANGELOG: '/changelog',
  FEATURE_REQUEST: 'https://eventoswiki.userjot.com/',
  BUG_REPORT: 'https://eventoswiki.userjot.com/',
}
