import type { Slug } from '@/shared/domain/types/slug'

export const Urls = {
  HOME: '/',
  EVENTS: '/events/',
  EVENTS_WITH_PROVINCE: (province: string) => `${Urls.EVENTS}?province=${province}`,
  MEETUPS: '/meetups/',
  MEETUPS_WITH_PROVINCE: (province: string) => `${Urls.MEETUPS}?province=${province}`,
  EVENT: (slug: Slug) => `/events/${slug}`,
  MEETUP: (slug: Slug) => `/meetups/${slug}`,
  PAST_EVENTS: '/events/past/',
  PAST_EVENTS_WITH_PROVINCE: (province: string) => `${Urls.PAST_EVENTS}?province=${province}`,
  PAST_MEETUPS: '/meetups/past/',
  PAST_MEETUPS_WITH_PROVINCE: (province: string) => `${Urls.PAST_MEETUPS}?province=${province}`,
  PROVINCE: (slug: Slug) => `/${slug}`,
  ORGANIZATION: (handle: string) => `/organizations/${handle}`,
  MY_ORGANIZATIONS: '/me/organizations/',
  CREATE_ORGANIZATION: '/me/organizations/create',
  CALENDAR: '/calendar',
  LOGIN: '/login',
  LOGIN_GITHUB: '/login/github',
  LOGIN_GOOGLE: '/login/google',
  LOGIN_TWITTER: '/login/twitter',
  LOGOUT: '/logout',
  PROFILE: '/me/profile',
  PRIVACY: '/privacy',
  TERMS: '/terms',
}
