export {
  PiCalendar as Calendar,
  PiCalendarBlank as CalendarBlank,
  PiChalkboard as Chalkboard,
  PiFacebookLogoFill as Facebook,
  PiGithubLogoFill as Github,
  PiInstagramLogoFill as Instagram,
  PiLaptop as Laptop,
  PiLink as Link,
  PiLinkedinLogoFill as Linkedin,
  PiMapPin as MapPin,
  PiMoon as Moon,
  PiSun as Sun,
  PiTwitchLogoFill as Twitch,
  PiTwitterLogoFill as Twitter,
  PiUsersFour as Users,
  PiYoutubeLogoFill as Youtube,
} from 'react-icons/pi'
