import { defineCollection, z } from 'astro:content'

const TAGS = [
  '.NET',
  'agile',
  'ai',
  'api',
  'api design',
  'architecture',
  'cloud',
  'data',
  'design',
  'devops',
  'devs',
  'diseño',
  'drupal',
  'frontend',
  'functional programming',
  'general',
  'geodatascience',
  'itsm',
  'java',
  'javascript',
  'joomla',
  'machine learning',
  'metaverse',
  'microsoft',
  'open source',
  'open space',
  'php',
  'python',
  'qa',
  'react',
  'security',
  'talleres',
  'testing',
  'ui/ux',
  'videojuegos',
  'web assembly',
  'wordpress',
] as const

const LOCATIONS = [
  'A Coruña',
  'Álava',
  'Albacete',
  'Alicante',
  'Almería',
  'Asturias',
  'Ávila',
  'Badajoz',
  'Barcelona',
  'Bizkaia',
  'Burgos',
  'Cáceres',
  'Cádiz',
  'Cantabria',
  'Castellón',
  'Ceuta',
  'Ciudad Real',
  'Córdoba',
  'Cuenca',
  'Gipuzkoa',
  'Girona',
  'Granada',
  'Guadalajara',
  'Huelva',
  'Huesca',
  'Islas Baleares',
  'Jaén',
  'La Rioja',
  'Las Palmas',
  'León',
  'Lleida',
  'Lugo',
  'Madrid',
  'Málaga',
  'Melilla',
  'Murcia',
  'Navarra',
  'Ourense',
  'Palencia',
  'Pontevedra',
  'Salamanca',
  'Santa Cruz de Tenerife',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Teruel',
  'Toledo',
  'Valencia',
  'Valladolid',
  'Zamora',
  'Zaragoza',
  'Online',
] as const

const events = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    shortDescription: z.string(),
    startsAt: z.date(),
    endsAt: z.date(),
    thumbnail: z.string(),
    image: z.string(),
    altImage: z.string().optional(),
    location: z.enum(LOCATIONS),
    web: z.string().url().optional(),
    twitter: z.string().url().optional(),
    linkedin: z.string().url().optional(),
    youtube: z.string().url().optional(),
    twitch: z.string().url().optional(),
    facebook: z.string().url().optional(),
    instagram: z.string().url().optional(),
    github: z.string().url().optional(),
    telegram: z.string().url().optional(),
    whatsapp: z.string().url().optional(),
    discord: z.string().url().optional(),
    tags: z.array(z.enum(TAGS)),
    tagColor: z.string(),
  }),
})

export const collections = {
  events,
}
